#!/bin/bash
#SBATCH --time=00:05:00
#SBATCH --mem=600
set -u
set -e
echo "Phasing $src_prefix ..."
[ -f "$genetic_map" ] || ( echo "Unable to locate '$genetic_map'"; exit 1 )
srun shapeit --input-bed "$src_prefix" \
	--input-map $genetic_map \
	--output-max "${dst_prefix}.haps" "${dst_prefix}.sample" \
	--output-log "${dst_prefix}.log"
srun shapeit -convert \
	--input-haps "${dst_prefix}" \
	--output-vcf "${dst_prefix}.vcf" \
	--output-log "${dst_prefix}.vcf.log"

