#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=2
#SBATCH --time=03:59:59
#SBATCH --mem=6gb

set -u
set -e

module load GATK

# a VCF file indexed by picard triggers an error with GATK
# easiest way to avoid this is to delete the VCF index if it exists.
rm -f "${input_vcf}.idx"
srun java \
   -XX:ParallelGCThreads=1  -Xmx4g \
   -Djava.io.tmpdir="$java_tmp" \
   -jar ${EBROOTGATK-dummy}/GenomeAnalysisTK.jar \
   -R "$genome_ref" \
   -T ASEReadCounter \
   -o "$output_csv" \
   -I "$input_bam" \
   -sites "$input_vcf" \
   -L "$input_vcf" \
   -U ALLOW_N_CIGAR_READS \
   -dt NONE \
   --minMappingQuality 10


